// Font Awesome Icon Mapping for Apps and Languages
export const ICON_MAP: Record<string, string> = {
    // Apps & Tools
    'github': 'fa-brands fa-github',
    'gitlab': 'fa-brands fa-gitlab',
    'bitbucket': 'fa-brands fa-bitbucket',
    'youtube': 'fa-brands fa-youtube',
    'stackoverflow': 'fa-brands fa-stack-overflow',
    'figma': 'fa-brands fa-figma',
    'discord': 'fa-brands fa-discord',
    'spotify': 'fa-brands fa-spotify',
    'chrome': 'fa-brands fa-chrome',
    'firefox': 'fa-brands fa-firefox',
    'edge': 'fa-brands fa-edge',
    'docker': 'fa-brands fa-docker',
    'aws': 'fa-brands fa-aws',
    'google': 'fa-brands fa-google',
    'linux': 'fa-brands fa-linux',
    'windows': 'fa-brands fa-windows',
    'apple': 'fa-brands fa-apple',
    'android': 'fa-brands fa-android',
    'jira': 'fa-brands fa-jira',
    'trello': 'fa-brands fa-trello',
    'slack': 'fa-brands fa-slack',
    // Removed incorrect brand icons; using custom SVG icons for Notion, ChatGPT, Gemini, and Claude

    // Languages & Frameworks (Font Awesome only)
    'js': 'fa-brands fa-js',
    'javascript': 'fa-brands fa-js',
    'python': 'fa-brands fa-python',
    'java': 'fa-brands fa-java',
    'php': 'fa-brands fa-php',
    'html': 'fa-brands fa-html5',
    'html5': 'fa-brands fa-html5',
    'css': 'fa-brands fa-css3-alt',
    'css3': 'fa-brands fa-css3-alt',
    'sql': 'fa-solid fa-database',
    'react': 'fa-brands fa-react',
    'vue': 'fa-brands fa-vuejs',
    'angular': 'fa-brands fa-angular',
    'node': 'fa-brands fa-node-js',
    'nodejs': 'fa-brands fa-node-js',
    'node.js': 'fa-brands fa-node-js',
    'laravel': 'fa-brands fa-laravel',
    'wordpress': 'fa-brands fa-wordpress',
};

// Technologies that use custom SVG icons (not Font Awesome)
export const CUSTOM_SVG_ICONS = [
    'vscode',
    'ts',
    'typescript',
    'cpp',
    'c++',
    'c',
    'csharp',
    'c#',
    'go',
    'rust',
    'cursor',
    'swift',
    'kotlin',
    'ruby',
    'notion',
    'chatgpt',
    'gemini',
    'claude',
    'sql',
];

// App Options for Dropdown
export const APP_OPTIONS = [
    { value: '', label: '-- Select App --' },
    { value: 'vscode', label: 'VS Code' },
    { value: 'github', label: 'GitHub' },
    { value: 'gitlab', label: 'GitLab' },
    { value: 'bitbucket', label: 'Bitbucket' },
    { value: 'youtube', label: 'YouTube' },
    { value: 'stackoverflow', label: 'Stack Overflow' },
    { value: 'figma', label: 'Figma' },
    { value: 'discord', label: 'Discord' },
    { value: 'spotify', label: 'Spotify' },
    { value: 'chrome', label: 'Chrome' },
    { value: 'firefox', label: 'Firefox' },
    { value: 'edge', label: 'Edge' },
    { value: 'docker', label: 'Docker' },
    { value: 'aws', label: 'AWS' },
    { value: 'google', label: 'Google' },
    { value: 'linux', label: 'Linux' },
    { value: 'windows', label: 'Windows' },
    { value: 'apple', label: 'Apple' },
    { value: 'android', label: 'Android' },
    { value: 'jira', label: 'Jira' },
    { value: 'trello', label: 'Trello' },
    { value: 'slack', label: 'Slack' },
    { value: 'notion', label: 'Notion' },
    { value: 'chatgpt', label: 'ChatGPT' },
    { value: 'gemini', label: 'Gemini' },
    { value: 'claude', label: 'Claude' },
    { value: 'cursor', label: 'Cursor' },
];

// Language Options for Dropdown
export const LANG_OPTIONS = [
    { value: '', label: '-- Select Language --' },
    { value: 'ts', label: 'TypeScript' },
    { value: 'js', label: 'JavaScript' },
    { value: 'python', label: 'Python' },
    { value: 'java', label: 'Java' },
    { value: 'cpp', label: 'C++' },
    { value: 'c', label: 'C' },
    { value: 'csharp', label: 'C#' },
    { value: 'go', label: 'Go' },
    { value: 'rust', label: 'Rust' },
    { value: 'php', label: 'PHP' },
    { value: 'ruby', label: 'Ruby' },
    { value: 'swift', label: 'Swift' },
    { value: 'kotlin', label: 'Kotlin' },
    { value: 'html', label: 'HTML' },
    { value: 'css', label: 'CSS' },
    { value: 'sql', label: 'SQL' },
    { value: 'react', label: 'React' },
    { value: 'vue', label: 'Vue' },
    { value: 'angular', label: 'Angular' },
    { value: 'nodejs', label: 'Node.js' },
    { value: 'laravel', label: 'Laravel' },
    { value: 'wordpress', label: 'WordPress' },
];
